# Site wide configuration
title: Thomas HUMMEL
locale: en_US
url:


# Jekyll configuration
permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Thomas HUMMEL
  avatar: profil.jpg
  bio: "French Ruby Developer<br/>
    31 years old<br/>
    Driving licence<br/>
    <a href='https://www.google.fr/maps/place/Grenoble/@45.1841656,5.7155424,13z/data=!3m1!4b1!4m2!3m1!1s0x478af48bd689be6f:0x618c10cd6e995398' target='blank'>Grenoble</a> (FRANCE)"
  email: thomas.hummel.link
  disqus-shortname:
  twitter: thooams
  facebook: #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: thooams
  stackoverflow: #http://stackoverflow.com/users/123456/username
  linkedin: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]


collections:
  portfolio:
    output: true
